name: run

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 00 01 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run main
        env:
          GLADOS: ${{ eyJ1c2VySWQiOjY0MjY0MSwiX2V4cGlyZSI6MTc4ODA3MjE3MjkyNSwiX21heEFnZSI6MjU5MjAwMDAwMDB9 }}
          NOTIFY: ${{ secrets.NOTIFY }}
